### PR TITLE
Fool Polymer 2.6+ into sending notifications

### PR DESCRIPTION
**Pull request by alshakero**
See: https://github.com/Polymer/polymer/commit/e6d558ec

### CODE REVIEW

**Comment by tomalec** [comment]
I'd actually add those two lines to `juicy-html` 
```js
JuicyHTMLElement.__dataHasAccessor = {/*partial: true, viewModel: true, */model: true};
JuicyHTMLElement.__isPropertyEffectsClient = true;
```

BTW, why do we need `partial: true, viewModel: true, ` here? those elements receive model attribute & property only

**Comment by alshakero** [comment]
Solid point

**Comment by tomalec** [comment]
The only comment that remains is for `partial: true, viewModel: true,`

**Comment by alshakero** [comment]
I removed them and tests blew up 🤕

**Comment by alshakero** [comment]
I'll merge for the mean and we can track this non-harmful issue later. I've been context-switching all day and it would be cool to finish this.

**Comment by tomalec** [comment]
I created an issue to check it after the hotfix.

**Pull request merged**
